const fs = require("fs");
const path = require("path");
const os = require("os");
const crypto = require("crypto");
const { spawnSync } = require("child_process");
const readline = require("readline");
const {
    normalizeMongoUri,
    quoteEnvValue,
    readMongoUriFromEnvContents,
} = require("./mongoUri");

const DEFAULT_CLIENT_URL = "https://aluxie07.github.io/IWP-HomeShare";

function escapePowerShellSingleQuoted(value) {
    return String(value).replace(/'/g, "''");
}

function buildEnvFile({ mongoUri, adminEmail, jwtSecret }) {
    const lines = [
        "# HomeShare local server — generated by setup wizard",
        "FILE_STORAGE=disk",
        "SKIP_RECAPTCHA=true",
        "PORT=8080",
        `CLIENT_URL=${DEFAULT_CLIENT_URL}`,
        `ALLOWED_ORIGINS=${DEFAULT_CLIENT_URL},http://localhost:3000,http://127.0.0.1:3000,http://localhost:8080,http://127.0.0.1:8080`,
        `JWT_SECRET=${jwtSecret}`,
        `MONGO_URI=${quoteEnvValue(normalizeMongoUri(mongoUri))}`,
        "",
    ];

    if (adminEmail) {
        lines.push(`ADMIN_EMAIL=${adminEmail}`);
        lines.push(`LOCAL_SYNC_OWNER_EMAIL=${adminEmail}`);
        lines.push("");
    } else {
        lines.push("# Optional — make this email an admin:");
        lines.push("# ADMIN_EMAIL=you@example.com");
        lines.push("");
    }

    lines.push("# Optional email (Brevo API):");
    lines.push("# BREVO_API_KEY=xkeysib-...");
    lines.push("# EMAIL_FROM=your-verified-sender@example.com");
    lines.push("");

    return lines.join("\n");
}

function needsSetup(envPath) {
    if (!fs.existsSync(envPath)) {
        return true;
    }
    const contents = fs.readFileSync(envPath, "utf8");
    if (contents.includes("USER:PASSWORD@cluster")) {
        return true;
    }
    if (contents.includes("change-this-to-a-long-random-string")) {
        return true;
    }
    const mongo = readMongoUriFromEnvContents(contents);
    if (!mongo || mongo.includes("USER:PASSWORD")) {
        return true;
    }
    return false;
}

function runWindowsGuiWizard() {
    const outFile = path.join(
        os.tmpdir(),
        `homeshare-setup-${process.pid}-${Date.now()}.json`
    );
    const outFilePs = escapePowerShellSingleQuoted(outFile);

    const ps1 = `
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

$form = New-Object System.Windows.Forms.Form
$form.Text = "HomeShare Local Server Setup"
$form.Size = New-Object System.Drawing.Size(560, 280)
$form.StartPosition = "CenterScreen"
$form.FormBorderStyle = "FixedDialog"
$form.MaximizeBox = $false
$form.MinimizeBox = $false
$form.TopMost = $true

$labelTitle = New-Object System.Windows.Forms.Label
$labelTitle.Text = "Set up your local HomeShare server"
$labelTitle.Font = New-Object System.Drawing.Font("Segoe UI", 11, [System.Drawing.FontStyle]::Bold)
$labelTitle.Location = New-Object System.Drawing.Point(16, 14)
$labelTitle.AutoSize = $true
$form.Controls.Add($labelTitle)

$labelMongo = New-Object System.Windows.Forms.Label
$labelMongo.Text = "MongoDB connection URI (required)"
$labelMongo.Location = New-Object System.Drawing.Point(16, 52)
$labelMongo.AutoSize = $true
$form.Controls.Add($labelMongo)

$textMongo = New-Object System.Windows.Forms.TextBox
$textMongo.Location = New-Object System.Drawing.Point(16, 74)
$textMongo.Size = New-Object System.Drawing.Size(510, 24)
$textMongo.Text = "mongodb+srv://USER:PASSWORD@cluster.mongodb.net/homeshare"
$form.Controls.Add($textMongo)

$labelAdmin = New-Object System.Windows.Forms.Label
$labelAdmin.Text = "Admin email (optional)"
$labelAdmin.Location = New-Object System.Drawing.Point(16, 114)
$labelAdmin.AutoSize = $true
$form.Controls.Add($labelAdmin)

$textAdmin = New-Object System.Windows.Forms.TextBox
$textAdmin.Location = New-Object System.Drawing.Point(16, 136)
$textAdmin.Size = New-Object System.Drawing.Size(510, 24)
$form.Controls.Add($textAdmin)

$labelHint = New-Object System.Windows.Forms.Label
$labelHint.Text = "Get a free URI from MongoDB Atlas. Then open the website and click Detect local server."
$labelHint.Location = New-Object System.Drawing.Point(16, 172)
$labelHint.Size = New-Object System.Drawing.Size(510, 32)
$form.Controls.Add($labelHint)

$btnOk = New-Object System.Windows.Forms.Button
$btnOk.Text = "Save and start"
$btnOk.Location = New-Object System.Drawing.Point(300, 210)
$btnOk.Size = New-Object System.Drawing.Size(110, 28)
$btnOk.DialogResult = [System.Windows.Forms.DialogResult]::OK
$form.AcceptButton = $btnOk
$form.Controls.Add($btnOk)

$btnCancel = New-Object System.Windows.Forms.Button
$btnCancel.Text = "Cancel"
$btnCancel.Location = New-Object System.Drawing.Point(416, 210)
$btnCancel.Size = New-Object System.Drawing.Size(110, 28)
$btnCancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.CancelButton = $btnCancel
$form.Controls.Add($btnCancel)

$result = $form.ShowDialog()
if ($result -ne [System.Windows.Forms.DialogResult]::OK) {
  exit 2
}

$mongo = $textMongo.Text.Trim()
$admin = $textAdmin.Text.Trim()
if (-not $mongo -or $mongo -match "USER:PASSWORD") {
  [System.Windows.Forms.MessageBox]::Show("Enter a real MongoDB URI (not the placeholder).","HomeShare") | Out-Null
  exit 3
}

$payload = @{ mongoUri = $mongo; adminEmail = $admin } | ConvertTo-Json -Compress
[System.IO.File]::WriteAllText('${outFilePs}', $payload)
exit 0
`.trim();

    const scriptPath = path.join(
        os.tmpdir(),
        `homeshare-setup-${process.pid}.ps1`
    );
    fs.writeFileSync(scriptPath, ps1, "utf8");

    try {
        const result = spawnSync(
            "powershell.exe",
            ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", scriptPath],
            {
                windowsHide: false,
                encoding: "utf8",
                timeout: 15 * 60 * 1000,
            }
        );

        if (result.status !== 0) {
            console.log(`  Setup window exited with code ${result.status || "unknown"}.`);
            return null;
        }

        if (!fs.existsSync(outFile)) {
            console.log("  Setup did not save your answers. Trying console setup instead.");
            return null;
        }

        const raw = fs.readFileSync(outFile, "utf8").replace(/^\uFEFF/, "");
        const parsed = JSON.parse(raw);
        return {
            mongoUri: String(parsed.mongoUri || "").trim(),
            adminEmail: String(parsed.adminEmail || "").trim(),
        };
    } catch (err) {
        console.log(`  Setup window failed: ${err.message || err}`);
        return null;
    } finally {
        try {
            fs.unlinkSync(scriptPath);
        } catch {
            // ignore
        }
        try {
            fs.unlinkSync(outFile);
        } catch {
            // ignore
        }
    }
}

function ask(question) {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
    });
    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            rl.close();
            resolve(String(answer || "").trim());
        });
    });
}

async function runConsoleWizard() {
    console.log("");
    console.log("  HomeShare Local Server — first-time setup");
    console.log("  =========================================");
    console.log("");

    let mongoUri = "";
    while (!mongoUri || mongoUri.includes("USER:PASSWORD")) {
        mongoUri = await ask("  MongoDB URI: ");
        if (!mongoUri || mongoUri.includes("USER:PASSWORD")) {
            console.log("  Please paste your real mongodb+srv://... connection string.");
        }
    }

    const adminEmail = await ask("  Admin email (optional, Enter to skip): ");
    return { mongoUri, adminEmail };
}

/**
 * Shows a setup UI (Windows popup when possible) and writes .env.
 * Returns true if setup completed, false if user cancelled.
 */
async function runSetupWizard(envPath) {
    let answers = null;

    if (process.platform === "win32") {
        console.log("  Opening setup window…");
        answers = runWindowsGuiWizard();
    }

    if (!answers) {
        answers = await runConsoleWizard();
    }

    if (!answers?.mongoUri || answers.mongoUri.includes("USER:PASSWORD")) {
        return false;
    }

    const mongoUri = normalizeMongoUri(answers.mongoUri);
    const jwtSecret = crypto.randomBytes(32).toString("hex");
    const contents = buildEnvFile({
        mongoUri,
        adminEmail: answers.adminEmail,
        jwtSecret,
    });

    fs.mkdirSync(path.dirname(envPath), { recursive: true });
    fs.writeFileSync(envPath, contents, "utf8");

    const saved = fs.readFileSync(envPath, "utf8");
    if (!saved.includes(mongoUri)) {
        console.error(`  Could not write config to ${envPath}`);
        return false;
    }

    console.log(`  Saved config: ${envPath}`);
    return true;
}

module.exports = {
    needsSetup,
    runSetupWizard,
    buildEnvFile,
    DEFAULT_CLIENT_URL,
};
